[package]
name = "openbook-v2-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.3.0", features = ["derive"] }
libfuzzer-sys = "0.4"

[dependencies.openbook-v2]
path = ".."
features = ["enable-gpl"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "multiple_orders"
path = "fuzz_targets/multiple_orders.rs"
test = false
doc = false
